import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/landing/Navbar/Navbar"
import { Montserrat } from 'next/font/google'
import Footer from "@/app/landing/Footer/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // según lo que uses
  variable: '--font-montserrat',        // para usar como variable si deseas
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <NavBar />

        {children}
        <Footer/>
      </body>
    </html>
  );
}
